-- V10: Add missing indexes, unique constraints, and audit/tracking tables
-- Generated by Enterprise Audit 2026-06-25

-- ============================================================
-- SECTION 1: Missing indexes on core tables (performance fixes)
-- ============================================================

-- attendance.student_id index (PERF-05)
CREATE INDEX IF NOT EXISTS idx_attendance_student_id
    ON attendance(student_id);

-- student_fee_assignment scoped queries
CREATE INDEX IF NOT EXISTS idx_student_fee_assignment_school_academic
    ON student_fee_assignments(school_id, academic_year);

-- sms_log date-filtered history
CREATE INDEX IF NOT EXISTS idx_sms_log_school_created
    ON sms_logs(school_id, created_at);

-- messages school + sender index
CREATE INDEX IF NOT EXISTS idx_message_school_sender
    ON messages(school_id, sender_id);

-- notifications school + user index
CREATE INDEX IF NOT EXISTS idx_notification_school_user
    ON app_notifications(school_id, user_id);

-- marks composite index
CREATE INDEX IF NOT EXISTS idx_marks_student_school
    ON marks(student_id, school_id);

CREATE INDEX IF NOT EXISTS idx_marks_school_exam
    ON marks(school_id, exam_type);

-- ============================================================
-- SECTION 2: Unique constraint on marks to prevent duplicates
-- ============================================================

-- Prevent duplicate marks entries for same student+subject+examType+school
ALTER TABLE marks
    ADD CONSTRAINT IF NOT EXISTS uq_marks_student_subject_exam_school
    UNIQUE (student_id, subject, exam_type, school_id);

-- ============================================================
-- SECTION 3: Marks audit log table
-- ============================================================

CREATE TABLE IF NOT EXISTS marks_audit_log (
    id           BIGSERIAL PRIMARY KEY,
    marks_id     BIGINT       NOT NULL,
    action       VARCHAR(10)  NOT NULL CHECK (action IN ('CREATE','UPDATE','DELETE')),
    student_id   BIGINT       NOT NULL,
    student_name VARCHAR(200),
    subject      VARCHAR(100),
    exam_type    VARCHAR(100),
    old_marks    NUMERIC(6,2),
    new_marks    NUMERIC(6,2),
    old_grade    VARCHAR(10),
    new_grade    VARCHAR(10),
    changed_by   BIGINT       NOT NULL,
    changed_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    school_id    BIGINT       NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_marks_audit_school_student
    ON marks_audit_log(school_id, student_id);

CREATE INDEX IF NOT EXISTS idx_marks_audit_changed_at
    ON marks_audit_log(changed_at);

-- ============================================================
-- SECTION 4: Message reads table (replaces comma-string readByUserIds)
-- ============================================================

CREATE TABLE IF NOT EXISTS message_reads (
    message_id  BIGINT    NOT NULL,
    user_id     BIGINT    NOT NULL,
    read_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (message_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_message_reads_user
    ON message_reads(user_id);

-- ============================================================
-- SECTION 5: School authentication config table
-- ============================================================

CREATE TABLE IF NOT EXISTS school_auth_config (
    school_id                BIGINT      PRIMARY KEY REFERENCES schools(id) ON DELETE CASCADE,
    student_login_method     VARCHAR(30) NOT NULL DEFAULT 'EMAIL_OR_ADMISSION'
                                 CHECK (student_login_method IN ('EMAIL_ONLY','ADMISSION_ONLY','EMAIL_OR_ADMISSION')),
    email_mandatory_students BOOLEAN     NOT NULL DEFAULT TRUE,
    email_verification       BOOLEAN     NOT NULL DEFAULT TRUE,
    forgot_password_method   VARCHAR(20) NOT NULL DEFAULT 'EMAIL_OTP'
                                 CHECK (forgot_password_method IN ('EMAIL_OTP','MOBILE_OTP','BOTH')),
    allow_self_signup        BOOLEAN     NOT NULL DEFAULT TRUE,
    session_timeout_minutes  INT         NOT NULL DEFAULT 60,
    max_failed_attempts      INT         NOT NULL DEFAULT 5,
    created_at               TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- ============================================================
-- SECTION 6: School diary config table
-- ============================================================

CREATE TABLE IF NOT EXISTS school_diary_config (
    school_id               BIGINT      PRIMARY KEY REFERENCES schools(id) ON DELETE CASCADE,
    diary_mode              VARCHAR(20) NOT NULL DEFAULT 'SUBJECT_TEACHER'
                                CHECK (diary_mode IN ('COORDINATOR','CLASS_TEACHER','SUBJECT_TEACHER','HYBRID')),
    coordinator_user_id     BIGINT      REFERENCES users(id) ON DELETE SET NULL,
    requires_approval       BOOLEAN     NOT NULL DEFAULT FALSE,
    notify_students_push    BOOLEAN     NOT NULL DEFAULT TRUE,
    notify_parents_whatsapp BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- ============================================================
-- SECTION 7: Normalize school features (separate from JSON blob)
-- ============================================================

CREATE TABLE IF NOT EXISTS school_features (
    school_id    BIGINT       NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    feature_key  VARCHAR(100) NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled_by   BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    enabled_at   TIMESTAMP,
    expires_at   TIMESTAMP,
    notes        TEXT,
    PRIMARY KEY (school_id, feature_key)
);

CREATE INDEX IF NOT EXISTS idx_school_features_school
    ON school_features(school_id);

-- ============================================================
-- SECTION 8: Exam type lock and publish columns
-- ============================================================

ALTER TABLE exam_types
    ADD COLUMN IF NOT EXISTS marks_locked_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS marks_published   BOOLEAN NOT NULL DEFAULT FALSE;

-- ============================================================
-- SECTION 9: Broadcast delivery audit
-- ============================================================

CREATE TABLE IF NOT EXISTS broadcast_delivery_log (
    id           BIGSERIAL   PRIMARY KEY,
    message_id   BIGINT      NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    recipient_id BIGINT      NOT NULL,
    delivered_at TIMESTAMP,
    read_at      TIMESTAMP,
    push_sent    BOOLEAN     NOT NULL DEFAULT FALSE,
    push_status  VARCHAR(20),
    school_id    BIGINT      NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_broadcast_delivery_message
    ON broadcast_delivery_log(message_id);

CREATE INDEX IF NOT EXISTS idx_broadcast_delivery_recipient
    ON broadcast_delivery_log(recipient_id);
