/**
 * Application Constants
 */

// Business Types
export const BUSINESS_TYPES = {
  RESTAURANT: 'RESTAURANT',
  CAFE: 'CAFE',
  GROCERY: 'GROCERY',
  RETAIL: 'RETAIL',
  OTHER: 'OTHER',
};

// Subscription Tiers
export const SUBSCRIPTION_TIERS = {
  BASIC: 'BASIC',
  PREMIUM: 'PREMIUM',
  ENTERPRISE: 'ENTERPRISE',
};

// Subscription Status
export const SUBSCRIPTION_STATUS = {
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  CANCELED: 'CANCELED',
};

// Order Status
export const ORDER_STATUS = {
  CART: 'CART',
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  PREPARING: 'PREPARING',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED',
  REFUNDED: 'REFUNDED',
};

// Payment Methods
export const PAYMENT_METHODS = {
  CASH: 'CASH',
  CARD: 'CARD',
  ONLINE: 'ONLINE',
  UPI: 'UPI',
};

// Payment Status
export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

// Delivery Types
export const DELIVERY_TYPES = {
  DELIVERY: 'DELIVERY',
  PICKUP: 'PICKUP',
};

// Message Template Types
export const MESSAGE_TEMPLATE_TYPES = {
  GREETING: 'GREETING',
  MENU: 'MENU',
  ORDER_CONFIRMATION: 'ORDER_CONFIRMATION',
  PAYMENT_REQUEST: 'PAYMENT_REQUEST',
  FAQ: 'FAQ',
};

// WhatsApp Chat Session States
export const SESSION_STATES = {
  MENU: 'MENU',
  CATEGORY_VIEW: 'CATEGORY_VIEW',
  PRODUCT_VIEW: 'PRODUCT_VIEW',
  CART: 'CART',
  CHECKOUT: 'CHECKOUT',
  ABANDONED: 'ABANDONED',
};

// Notification Types
export const NOTIFICATION_TYPES = {
  NEW_ORDER: 'NEW_ORDER',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  CUSTOMER_MESSAGE: 'CUSTOMER_MESSAGE',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
};

// Audit Log Status
export const AUDIT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
};

// OTP Purpose
export const OTP_PURPOSE = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  PASSWORD_RESET: 'PASSWORD_RESET',
};

// Error Codes
export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_LIMIT_EXCEEDED: 'OTP_LIMIT_EXCEEDED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};

// Audit Actions
export const AUDIT_ACTIONS = {
  USER_SIGNUP: 'USER_SIGNUP',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_UPDATE: 'USER_UPDATE',
  BUSINESS_CREATE: 'BUSINESS_CREATE',
  BUSINESS_UPDATE: 'BUSINESS_UPDATE',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_CANCEL: 'ORDER_CANCEL',
  PAYMENT_PROCESS: 'PAYMENT_PROCESS',
  REFUND_PROCESS: 'REFUND_PROCESS',
  WHATSAPP_MESSAGE_FAILED: 'WHATSAPP_MESSAGE_FAILED',
};

// Database Table Prefixes
export const DB_TABLE_PREFIX = 'wa_';

// Cache Keys
export const CACHE_KEYS = {
  USER: (userId) => `wa:user:${userId}`,
  BUSINESS: (businessId) => `wa:business:${businessId}`,
  PRODUCTS: (businessId) => `wa:products:${businessId}`,
  CUSTOMERS: (businessId) => `wa:customers:${businessId}`,
  ORDERS: (businessId) => `wa:orders:${businessId}`,
  SESSION: (sessionId) => `wa:session:${sessionId}`,
};

// Email Templates
export const EMAIL_TEMPLATES = {
  WELCOME: 'welcome',
  VERIFICATION: 'verification',
  OTP: 'otp',
  PASSWORD_RESET: 'password_reset',
  ORDER_CONFIRMATION: 'order_confirmation',
  PAYMENT_SUCCESS: 'payment_success',
};

// File Upload Limits
export const FILE_LIMITS = {
  LOGO_SIZE: 5 * 1024 * 1024, // 5MB
  PRODUCT_IMAGE_SIZE: 5 * 1024 * 1024, // 5MB
  DOCUMENT_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/webp'],
};

// API Pagination
export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export default {
  BUSINESS_TYPES,
  SUBSCRIPTION_TIERS,
  SUBSCRIPTION_STATUS,
  ORDER_STATUS,
  PAYMENT_METHODS,
  PAYMENT_STATUS,
  DELIVERY_TYPES,
  MESSAGE_TEMPLATE_TYPES,
  SESSION_STATES,
  NOTIFICATION_TYPES,
  AUDIT_STATUS,
  OTP_PURPOSE,
  ERROR_CODES,
  AUDIT_ACTIONS,
  DB_TABLE_PREFIX,
  CACHE_KEYS,
  EMAIL_TEMPLATES,
  FILE_LIMITS,
  PAGINATION,
  HTTP_STATUS,
};
