/**
 * authService.js
 * Authenticates against the Spring Boot backend only.
 * OTP is generated by backend, stored in users.reset_otp + users.otp_expiry columns.
 */
import { authAPI } from './api';

/**
 * Login with email + password.
 */
export const loginWithEmail = async (email, password, selectedRole) => {
  try {
    const res  = await authAPI.login({ email, password, selectedRole });
    const body  = res.data?.data ?? res.data;
    if (body?.otpRequired) {
      return { otpRequired: true, email: body.otpEmail ?? body.email ?? email };
    }
    const token = body?.token ?? body?.accessToken ?? body?.jwt;
    const user  = body?.user  ?? (body?.role || body?.email ? body : null);
    if (!token || !user?.role) {
      throw new Error('Unexpected response from server. Please try again.');
    }
    const normalizedUser = {
      ...user,
      role: String(user.role).toUpperCase(),
      isCoordinator: user.isCoordinator === true,
    };
    return { user: normalizedUser, token };
  } catch (apiErr) {
    const isColdStart = !apiErr.response || [502, 503, 504].includes(apiErr.response?.status);
    const msg = isColdStart
      ? 'Server is starting up. Please wait...'
      : (apiErr.response?.data?.message
          || apiErr.response?.data?.error
          || 'Invalid credentials. Please check your email and password.');
    const error = new Error(msg);
    error.isColdStart = isColdStart;
    throw error;
  }
};

export const verifyOwnerOtp = async (email, otp) => {
  try {
    const res  = await authAPI.verifyOwnerOtp({ email, otp });
    const body  = res.data?.data ?? res.data;
    const token = body?.token ?? body?.accessToken ?? body?.jwt;
    const user  = body?.user  ?? (body?.role || body?.email ? body : null);
    if (!token || !user?.role) {
      throw new Error('Unexpected response from server. Please try again.');
    }
    return { user: { ...user, role: String(user.role).toUpperCase() }, token };
  } catch (err) {
    const msg = err.response?.data?.message
      || err.response?.data?.error
      || err.message
      || 'Invalid OTP. Please try again.';
    throw new Error(msg);
  }
};

/**
 * Send OTP to mobile.
 * Backend generates OTP, stores in users.reset_otp & users.otp_expiry, sends via SMS.
 * Throws if mobile is not registered.
 */
export const requestOTP = async (mobile) => {
  const res = await authAPI.forgotPassword({ mobile });
  return { sent: true, data: res?.data };
};

/**
 * Verify OTP entered by user against backend (checks users.reset_otp column).
 * Returns authenticated user + JWT token on success.
 */
export const verifyOTP = async (mobile, otp) => {
  try {
    const res   = await authAPI.verifyOTP({ mobile, otp });
    const body  = res.data?.data ?? res.data;
    const token = body?.token ?? body?.accessToken ?? body?.jwt;
    const user  = body?.user  ?? (body?.role || body?.email || body?.mobile ? body : null);
    if (!token || !user?.role) {
      throw new Error('Unexpected response from server. Please try again.');
    }
    return { user: { ...user, role: String(user.role).toUpperCase() }, token };
  } catch (err) {
    const msg = err.response?.data?.message
      || err.response?.data?.error
      || err.message
      || 'Invalid OTP. Please try again.';
    throw new Error(msg);
  }
};

/**
 * Reset / change password.
 */
export const changePassword = async (payload) => {
  try {
    await authAPI.changePassword(payload);
    return { success: true };
  } catch (err) {
    const msg = err.response?.data?.message || err.message || 'Password change failed';
    return { success: false, message: msg };
  }
};

export default { loginWithEmail, verifyOwnerOtp, requestOTP, verifyOTP, changePassword };
